# Generated by Django 2.2.2 on 2020-03-04 23:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified', models.BooleanField()),
                ('contact', models.IntegerField()),
                ('auth_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Global_item_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('remaining', models.IntegerField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='History_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Region_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=50)),
                ('pin', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Role_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Shop_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noti_flag', models.BooleanField()),
                ('adderes', models.CharField(max_length=30)),
                ('contact_no', models.IntegerField()),
                ('region_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ration.Region_table')),
                ('shopkeeper_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ration.Account_table')),
            ],
        ),
        migrations.CreateModel(
            name='Shop_item_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('remaining', models.IntegerField()),
                ('price', models.FloatField()),
                ('mainitem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ration.Global_item_table')),
                ('shop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ration.Shop_table')),
            ],
        ),
        migrations.CreateModel(
            name='Maintainance_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('is_super', models.BooleanField()),
                ('History_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ration.History_table')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ration.Global_item_table')),
                ('shop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ration.Shop_table')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ration.Account_table')),
            ],
        ),
        migrations.AddField(
            model_name='account_table',
            name='role_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ration.Role_table'),
        ),
    ]
