# Generated by Django 2.2.2 on 2020-03-05 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ration', '0002_auto_20200305_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_table',
            name='contact',
            field=models.CharField(max_length=10),
        ),
    ]
