# Generated by Django 2.2.2 on 2020-03-05 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ration', '0003_auto_20200305_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_table',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shop_table',
            name='is_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account_table',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
