# Generated by Django 2.2.2 on 2020-03-05 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ration', '0004_auto_20200305_1328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop_table',
            old_name='adderes',
            new_name='address',
        ),
    ]
