# Generated by Django 2.2.2 on 2020-03-06 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ration', '0005_auto_20200305_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='global_item_table',
            name='History_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ration.History_table'),
        ),
    ]
