# Generated by Django 2.2 on 2020-03-14 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ration', '0007_region_table_is_open'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('address', models.TextField()),
                ('contact_no', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=30)),
                ('qualification', models.IntegerField(choices=[(1, 'Master Degree'), (2, "Bachelor's Degree"), (3, '12th Pass'), (4, '10th Pass'), (5, 'Below 10th')])),
                ('is_accepted', models.BooleanField(default=False)),
            ],
        ),
    ]
