# Generated by Django 2.2 on 2020-03-14 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ration', '0008_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='region_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ration.Region_table'),
        ),
    ]
