# Generated by Django 2.2 on 2020-03-17 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ration', '0014_auto_20200315_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monthly_Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('history_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ration.History_table')),
                ('shop_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ration.Shop_table')),
            ],
        ),
    ]
